# Credits

This is heavily based on https://github.com/pytorch/tutorials

# What is PyTorch?

> **NOTE** In the last part of this lab cuda is used. If you have a cuda enabled machine, read the README.md in the root of this repo on how to use nvidia-docker.


It’s a Python based scientific computing package targeted at two sets of
audiences:
-  A replacement for numpy to use the power of GPUs
-  a deep learning research platform that provides maximum flexibility
   and speed


# Getting Started

In this lab you will get a quick start on what pytorch is and how to use it.

## 1. Tensors

Tensors are similar to numpy’s ndarrays, with the addition being that
Tensors can also be used on a GPU to accelerate computing.

In [2]:
import torch

Construct a 5x3 matrix, uninitialized

In [3]:
x = torch.Tensor(5, 3)
print(x)

tensor([[1.2743e+15, 4.4781e-41, 1.2743e+15],
        [4.4781e-41, 2.6045e-29, 2.6900e-35],
        [2.4267e-35, 3.9431e-34, 4.4255e-34],
        [3.0581e-29, 7.4043e-40, 1.1663e-38],
        [1.1663e-38, 2.9000e-29, 2.8405e-29]])


Construct a randomly initialized matrix

In [4]:
x = torch.rand(5, 3)
print(x)

tensor([[0.3475, 0.6064, 0.9490],
        [0.4270, 0.2072, 0.7258],
        [0.8439, 0.1446, 0.3245],
        [0.9901, 0.9100, 0.4288],
        [0.5238, 0.6467, 0.9901]])


Get its size

In [4]:
print(x.size())

torch.Size([5, 3])


**NOTE**: `torch.Size` is in fact a tuple, so it supports the same operations that a tuple supports.

In [5]:
x[1:3] = 2
print(x)

tensor([[0.2301, 0.5046, 0.1780],
        [2.0000, 2.0000, 2.0000],
        [2.0000, 2.0000, 2.0000],
        [0.4100, 0.2448, 0.0337],
        [0.6939, 0.9086, 0.8720]])


# Assignment

Make use of the pytorch docs <http://pytorch.org/docs/torch>
1. Make a tensor of size (2, 17)
2. Make a torch.FloatTensor of size (3, 1)
3. Make a torch.LongTensor of size (5, 2, 1)
  - fill the entire tensor with 7s
4. Make a torch.ByteTensor of size (5,)
  - fill the middle 3 indices with ones such that it records [0, 1, 1, 1, 0]

In [10]:
t1 = torch.Tensor(2, 17)
t2 = torch.FloatTensor(3, 1)
t3 = torch.ones(5, 2, 1, dtype=torch.long) * 7
t4 = torch.zeros(5, dtype=torch.uint8)
t4[1:4] = 1
t1, t2, t3, t4

(tensor([[ 6.9987e+06,  3.3160e-41,  7.2032e+06,  3.3160e-41,  1.1210e-43,
           0.0000e+00,  1.5695e-43,  0.0000e+00, -3.3962e+04,  7.0065e-45,
           8.4078e-44,  0.0000e+00,  0.0000e+00,  0.0000e+00,  0.0000e+00,
           0.0000e+00,  0.0000e+00],
         [ 0.0000e+00,  7.7052e+31,  1.9447e+31,  2.1715e-18,  2.3081e-12,
           2.6302e+20,  6.1943e-04,  3.6022e-12,  6.9989e+22,  2.6330e+20,
           6.1943e-04,  3.6022e-12,  7.1223e+28,  3.0958e-18,  2.6532e+20,
           1.9062e+37,  0.0000e+00]]),
 tensor([[-6.0969e-30],
         [ 3.3167e-41],
         [ 7.5148e+06]]),
 tensor([[[7],
          [7]],
 
         [[7],
          [7]],
 
         [[7],
          [7]],
 
         [[7],
          [7]],
 
         [[7],
          [7]]]),
 tensor([0, 1, 1, 1, 0], dtype=torch.uint8))

## 2. Operations
There are multiple syntaxes for operations. Let's see addition as an example:

### 2.1 Addition: syntax 1

In [6]:
y = torch.rand(5, 3)
print(x + y)

RuntimeError: ignored

### 2.2 Addition: syntax 2

In [12]:
print(torch.add(x, y))

tensor([[0.3004, 0.8735, 0.3883],
        [2.4298, 2.5614, 2.9318],
        [2.2825, 2.5407, 2.2130],
        [0.7125, 0.9898, 0.6440],
        [0.9390, 1.1952, 1.5714]])


### 2.3 Addition: giving an output tensor

In [13]:
result = torch.Tensor(5, 3)
torch.add(x, y, out=result)
print(result)

tensor([[0.3004, 0.8735, 0.3883],
        [2.4298, 2.5614, 2.9318],
        [2.2825, 2.5407, 2.2130],
        [0.7125, 0.9898, 0.6440],
        [0.9390, 1.1952, 1.5714]])


### 2.4 Addition: in-place

adds `x`to `y`

In [14]:
y.add_(x)
print(y)

tensor([[0.3004, 0.8735, 0.3883],
        [2.4298, 2.5614, 2.9318],
        [2.2825, 2.5407, 2.2130],
        [0.7125, 0.9898, 0.6440],
        [0.9390, 1.1952, 1.5714]])


**NOTE**: Any operation that mutates a tensor in-place is post-fixed with an `_`. For example: `x.copy_(y)`, `x.t_()`, will change `x`.

You can use standard numpy-like indexing with all bells and whistles!

In [15]:
print(x[:, 1])

tensor([0.5046, 2.0000, 2.0000, 0.2448, 0.9086])


**Read later** 100+ Tensor operations, including transposing, indexing, slicing, mathematical operations, linear algebra, random numbers, etc are described here <http://pytorch.org/docs/torch>

# Assignment

1. multiplication of two tensors (see [torch.Tensor.mul](http://pytorch.org/docs/master/tensors.html#torch.Tensor.mul))
2. do the same, but inplace
3. division of two tensors (see [torch.Tensor.div](http://pytorch.org/docs/master/tensors.html#torch.Tensor.div))
4. perform a matrix multiplication of two tensors of size (2, 4) and (4, 2)

In [16]:
result_mul = torch.mul(x, y)
print(result_mul)
print("Y before multiplication:", y)
y.mul_(x)
print("Y after multiplication:", y)

tensor([[0.0691, 0.4408, 0.0691],
        [4.8596, 5.1228, 5.8635],
        [4.5650, 5.0815, 4.4260],
        [0.2921, 0.2423, 0.0217],
        [0.6516, 1.0859, 1.3702]])


In [20]:
result_div = torch.div(x, y)
print(result_div)
print("Y before dividion:", y)
y.div_(x)
print("Y after dividion:", y)

tensor([[0.7660, 0.5777, 0.4585],
        [0.8231, 0.7808, 0.6822],
        [0.8762, 0.7872, 0.9037],
        [0.5754, 0.2473, 0.0523],
        [0.7391, 0.7602, 0.5549]])
Y before dividion: tensor([[0.3004, 0.8735, 0.3883],
        [2.4298, 2.5614, 2.9318],
        [2.2825, 2.5407, 2.2130],
        [0.7125, 0.9898, 0.6440],
        [0.9390, 1.1952, 1.5714]])
Y after dividion: tensor([[ 1.3055,  1.7310,  2.1810],
        [ 1.2149,  1.2807,  1.4659],
        [ 1.1413,  1.2704,  1.1065],
        [ 1.7378,  4.0438, 19.1140],
        [ 1.3531,  1.3154,  1.8021]])


In [19]:
t1 = torch.rand(2, 4)
t2 = torch.rand(4, 2)
print(torch.mul(t1, t2.T))

tensor([[0.0610, 0.0501, 0.4921, 0.1788],
        [0.3414, 0.3526, 0.1311, 0.0035]])


## 3. Numpy Bridge

Converting a torch Tensor to a numpy array and vice versa is a breeze.

The torch Tensor and numpy array will share their underlying memory locations, and changing one will change the other.

### 3.1 Converting torch Tensor to numpy Array

In [21]:
a = torch.ones(5)
print(a)

tensor([1., 1., 1., 1., 1.])


In [22]:
b = a.numpy()
print(b)

[1. 1. 1. 1. 1.]


See how the numpy array changed in value: the `numpy()` method provides a *view* of the original tensor, not a copy.

In [23]:
a.add_(1)
print(a)
print(b)

tensor([2., 2., 2., 2., 2.])
[2. 2. 2. 2. 2.]


### 3.2 Converting numpy Array to torch Tensor

See how changing the np array changed the torch Tensor automatically

In [24]:
import numpy as np
a = np.ones(5)
b = torch.from_numpy(a)
np.add(a, 1, out=a)
print(a)
print(b)

[2. 2. 2. 2. 2.]
tensor([2., 2., 2., 2., 2.], dtype=torch.float64)


# Assignment

1. create a tensor of size (5, 2) containing ones
2. now convert it to a numpy array
3. now convert it back to a torch tensor

In [25]:
t1 = torch.ones(5, 2)
t2 = t1.numpy()
t3 = torch.from_numpy(t2)
t1, t2, t3

(tensor([[1., 1.],
         [1., 1.],
         [1., 1.],
         [1., 1.],
         [1., 1.]]),
 array([[1., 1.],
        [1., 1.],
        [1., 1.],
        [1., 1.],
        [1., 1.]], dtype=float32),
 tensor([[1., 1.],
         [1., 1.],
         [1., 1.],
         [1., 1.],
         [1., 1.]]))

All the Tensors on the CPU except a CharTensor support converting to NumPy and back.

## 4 CUDA Tensors

Tensors can be moved onto GPU using the `.cuda` function.
This is not necessary, but check the `README.md` for details on how to use a GPU with docker.

In [7]:
# let us run this cell only if CUDA is available
if torch.cuda.is_available():
    x = x.cuda()
    y = y.cuda()
    z = x + y
    # Notice that the tensors are now of type torch.cuda.FloatTensor (notice the cuda in there)
    # This is meant as a tensor to be run on the GPU.
    # The .cuda() does this to any parameter it is applied to.
    print(x)
    print(y)
    print(z)
else:
    print("CUDA not available on your machine.")

tensor([[0.3475, 0.6064, 0.9490],
        [0.4270, 0.2072, 0.7258],
        [0.8439, 0.1446, 0.3245],
        [0.9901, 0.9100, 0.4288],
        [0.5238, 0.6467, 0.9901]], device='cuda:0')
tensor([[0.4152, 0.3809, 0.4930],
        [0.1829, 0.8728, 0.2884],
        [0.4362, 0.5915, 0.8035],
        [0.9663, 0.9562, 0.5076],
        [0.4910, 0.0514, 0.8091]], device='cuda:0')
tensor([[0.7628, 0.9873, 1.4420],
        [0.6098, 1.0801, 1.0142],
        [1.2801, 0.7361, 1.1280],
        [1.9564, 1.8662, 0.9364],
        [1.0147, 0.6981, 1.7992]], device='cuda:0')
